package net.yahya.vesture;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.Item;
import net.yahya.vesture.item.CosmeticItem;
import net.yahya.vesture.item.CosmeticSlot;

public class VestureItems {

    // Auto-generated item definitions
    public static final CosmeticItem AMULET = register("amulet", CosmeticSlot.CHEST, id("amulet_default"));
    public static final CosmeticItem ARM_GUARD = register("arm_guard", CosmeticSlot.HAND, null);
    public static final CosmeticItem ARMORERS_HAT = register("armorers_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem AVIATOR_CAP = register("aviator_cap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem BANDANA = register("bandana", CosmeticSlot.HEAD, null);
    public static final CosmeticItem BARBARIAN_SHORTS = register("barbarian_shorts", CosmeticSlot.LEGS, id("piglin_default"));
    public static final CosmeticItem BARBARIAN_TUNIC = register("barbarian_tunic", CosmeticSlot.CHEST, id("piglin_default"));
    public static final CosmeticItem BASEBALL_CAP = register("baseball_cap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem BEANIE = register("beanie", CosmeticSlot.HEAD, null);
    public static final CosmeticItem BEE_HAT = register("bee_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem BEE_SUIT = register("bee_suit", CosmeticSlot.CHEST, id("bee_friender"));
    public static final CosmeticItem BEE_WINGS = register("bee_wings", CosmeticSlot.BACK, id("bee_wings"));
    public static final CosmeticItem BICORNE = register("bicorne", CosmeticSlot.HEAD, null);
    public static final CosmeticItem BLOUSE = register("blouse", CosmeticSlot.CHEST, id("ari_default"));
    public static final CosmeticItem BOATER_HAT = register("boater_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem BOMBER_JACKET = register("bomber_jacket", CosmeticSlot.CHEST, id("ghast_pilot_default"));
    public static final CosmeticItem BONNET = register("bonnet", CosmeticSlot.HEAD, null);
    public static final CosmeticItem BOWLER_HAT = register("bowler_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem BOWTIE = register("bowtie", CosmeticSlot.CHEST, id("bowtie"));
    public static final CosmeticItem BRACELET = register("bracelet", CosmeticSlot.HAND, null);
    public static final CosmeticItem BRENDANS_HAT = register("brendans_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem BRIDGETS_HAT = register("bridgets_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem BUTCHERS_HAT = register("butchers_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem BUTTON_DOWN_SHIRT = register("button_down_shirt", CosmeticSlot.CHEST, id("party_steve"));
    public static final CosmeticItem CALEMS_HAT = register("calems_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem CAPOTAIN = register("capotain", CosmeticSlot.HEAD, null);
    public static final CosmeticItem CARTOGRAPHERS_MONOCLE = register("cartographers_monocle", CosmeticSlot.HEAD, null);
    public static final CosmeticItem CARVED_GOURD_HAT = register("carved_gourd_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem CHASUBLE_BOTTOM = register("chasuble_bottom", CosmeticSlot.LEGS, id("villager_cleric"));
    public static final CosmeticItem CHASUBLE_TOP = register("chasuble_top", CosmeticSlot.CHEST, id("villager_cleric"));
    public static final CosmeticItem CIRCLE_FRAMED_GLASSES = register("circle_framed_glasses", CosmeticSlot.HEAD, null);
    public static final CosmeticItem CIRCLE_FRAMED_SUNGLASSES = register("circle_framed_sunglasses", CosmeticSlot.HEAD, null);
    public static final CosmeticItem CONDUCTORS_CAP = register("conductors_cap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem COOKING_APRON_BOTTOM = register("cooking_apron_bottom", CosmeticSlot.LEGS, id("villager_butcher"));
    public static final CosmeticItem COOKING_APRON_TOP = register("cooking_apron_top", CosmeticSlot.CHEST, id("villager_butcher"));
    public static final CosmeticItem CROWN = register("crown", CosmeticSlot.HEAD, null);
    public static final CosmeticItem CUFF = register("cuff", CosmeticSlot.HAND, null);
    public static final CosmeticItem CUFFED_JACKET = register("cuffed_jacket", CosmeticSlot.CHEST, id("kai"));
    public static final CosmeticItem DAWNS_HAT = register("dawns_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem DESERT_HAT = register("desert_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem DESERT_ROBE_BOTTOM = register("desert_robe_bottom", CosmeticSlot.LEGS, id("villager_desert"));
    public static final CosmeticItem DESERT_ROBE_TOP = register("desert_robe_top", CosmeticSlot.CHEST, id("villager_desert"));
    public static final CosmeticItem DESICCATED_CAP = register("desiccated_cap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem DESICCATED_PANTS = register("desiccated_pants", CosmeticSlot.LEGS, id("parched"));
    public static final CosmeticItem DESICCATED_SHIRT = register("desiccated_shirt", CosmeticSlot.CHEST, id("parched"));
    public static final CosmeticItem DRAGON_WINGS = register("dragon_wings", CosmeticSlot.BACK, id("ender_dragon"));
    public static final CosmeticItem DRAMA_MASK = register("drama_mask", CosmeticSlot.HEAD, null);
    public static final CosmeticItem EARRINGS = register("earrings", CosmeticSlot.HEAD, null);
    public static final CosmeticItem ELIOS_HAT = register("elios_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem ENGINEERS_CAP = register("engineers_cap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem ETHANS_HAT = register("ethans_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem EVOKERS_ROBE_BOTTOM = register("evokers_robe_bottom", CosmeticSlot.LEGS, id("evoker"));
    public static final CosmeticItem EVOKERS_ROBE_TOP = register("evokers_robe_top", CosmeticSlot.CHEST, id("evoker"));
    public static final CosmeticItem FACE_MASK = register("face_mask", CosmeticSlot.HEAD, null);
    public static final CosmeticItem FARMERS_HAT = register("farmers_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem FEDORA = register("fedora", CosmeticSlot.HEAD, null);
    public static final CosmeticItem FISHERMANS_HAT = register("fishermans_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem FISHMONGERS_APRON_BOTTOM = register("fishmongers_apron_bottom", CosmeticSlot.LEGS, id("villager_fisherman"));
    public static final CosmeticItem FISHMONGERS_APRON_TOP = register("fishmongers_apron_top", CosmeticSlot.CHEST, id("villager_fisherman"));
    public static final CosmeticItem FLAT_CAP = register("flat_cap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem FLETCHERS_HAT = register("fletchers_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem FLORIANS_HAT = register("florians_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem FLOWER_CROWN = register("flower_crown", CosmeticSlot.HEAD, null);
    public static final CosmeticItem FLOWER_PIN = register("flower_pin", CosmeticSlot.HEAD, null);
    public static final CosmeticItem FRAMED_GLASSES = register("framed_glasses", CosmeticSlot.HEAD, null);
    public static final CosmeticItem FRAMED_SUNGLASSES = register("framed_sunglasses", CosmeticSlot.HEAD, null);
    public static final CosmeticItem FUR_LINED_BOOTS = register("fur_lined_boots", CosmeticSlot.FEET, id("villager_taiga_default"));
    public static final CosmeticItem GAUNTLET = register("gauntlet", CosmeticSlot.HAND, null);
    public static final CosmeticItem GHOST_HAT = register("ghost_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem GLASSES = register("glasses", CosmeticSlot.HEAD, null);
    public static final CosmeticItem GLORIAS_HAT = register("glorias_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem GLOVE = register("glove", CosmeticSlot.HAND, null);
    public static final CosmeticItem GOGGLES = register("goggles", CosmeticSlot.HEAD, null);
    public static final CosmeticItem GOURD_HAT = register("gourd_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem HAIR_BOW = register("hair_bow", CosmeticSlot.HEAD, null);
    public static final CosmeticItem HAIR_CLIP = register("hair_clip", CosmeticSlot.HEAD, null);
    public static final CosmeticItem HALO = register("halo", CosmeticSlot.HEAD, null);
    public static final CosmeticItem HEADSET = register("headset", CosmeticSlot.HEAD, null);
    public static final CosmeticItem HEART_PIN = register("heart_pin", CosmeticSlot.HEAD, null);
    public static final CosmeticItem HEAVY_BELT = register("heavy_belt", CosmeticSlot.CHEST, id("piglin_brute_default"));
    public static final CosmeticItem HILBERTS_HAT = register("hilberts_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem HILDAS_HAT = register("hildas_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem HOOD = register("hood", CosmeticSlot.HEAD, null);
    public static final CosmeticItem ILLUSIONERS_CAP = register("illusioners_cap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem ILLUSIONERS_ROBE_BOTTOM = register("illusioners_robe_bottom", CosmeticSlot.LEGS, id("illusioner"));
    public static final CosmeticItem ILLUSIONERS_ROBE_TOP = register("illusioners_robe_top", CosmeticSlot.CHEST, id("illusioner"));
    public static final CosmeticItem IMPERIAL_CROWN = register("imperial_crown", CosmeticSlot.HEAD, null);
    public static final CosmeticItem INSULATED_BOOTS = register("insulated_boots", CosmeticSlot.FEET, id("pillager"));
    public static final CosmeticItem JACK_O_LANTERN_HAT = register("jack_o_lantern_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem JEANS = register("jeans", CosmeticSlot.LEGS, id("sunny_default"));
    public static final CosmeticItem JESTERS_CAP = register("jesters_cap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem JOHNNYS_HAT = register("johnnys_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem JULIANAS_HAT = register("julianas_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem JUNGLE_PELT_BOTTOM = register("jungle_pelt_bottom", CosmeticSlot.LEGS, id("villager_jungle"));
    public static final CosmeticItem JUNGLE_PELT_TOP = register("jungle_pelt_top", CosmeticSlot.CHEST, id("villager_jungle"));
    public static final CosmeticItem KNEE_HIGH_BOOTS = register("knee_high_boots", CosmeticSlot.FEET, id("party_alex"));
    public static final CosmeticItem KNUCKLE = register("knuckle", CosmeticSlot.HAND, null);
    public static final CosmeticItem LEAFS_HAT = register("leafs_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem LEATHERWORKING_APRON_BOTTOM = register("leatherworking_apron_bottom", CosmeticSlot.LEGS, id("villager_leatherworker"));
    public static final CosmeticItem LEATHERWORKING_APRON_TOP = register("leatherworking_apron_top", CosmeticSlot.CHEST, id("villager_leatherworker"));
    public static final CosmeticItem LIBRARIANS_HAT = register("librarians_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem LOINCLOTH = register("loincloth", CosmeticSlot.LEGS, id("zombified_piglin"));
    public static final CosmeticItem LUCAS_HAT = register("lucas_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem LYRAS_HAT = register("lyras_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem MASONRY_APRON_BOTTOM = register("masonry_apron_bottom", CosmeticSlot.LEGS, id("villager_mason"));
    public static final CosmeticItem MASONRY_APRON_TOP = register("masonry_apron_top", CosmeticSlot.CHEST, id("villager_mason"));
    public static final CosmeticItem MAYS_HAT = register("mays_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem MINERS_HELMET = register("miners_helmet", CosmeticSlot.HEAD, null);
    public static final CosmeticItem NATES_HAT = register("nates_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem NIGHTCAP = register("nightcap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem OVERALLS = register("overalls", CosmeticSlot.CHEST, id("sunny_default"));
    public static final CosmeticItem PANTS = register("pants", CosmeticSlot.LEGS, id("steve"));
    public static final CosmeticItem PHRYGIAN_CAP = register("phrygian_cap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem PILLAGERS_TUNIC = register("pillagers_tunic", CosmeticSlot.CHEST, id("pillager"));
    public static final CosmeticItem PILOTS_HAT = register("pilots_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem PLAID_PANTS = register("plaid_pants", CosmeticSlot.LEGS, id("vindicator"));
    public static final CosmeticItem PLAINS_ROBE_BOTTOM = register("plains_robe_bottom", CosmeticSlot.LEGS, id("villager_plains"));
    public static final CosmeticItem PLAINS_ROBE_TOP = register("plains_robe_top", CosmeticSlot.CHEST, id("villager_plains"));
    public static final CosmeticItem PROPELLER_CAP = register("propeller_cap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem PROSTHETIC_ARM = register("prosthetic_arm", CosmeticSlot.HAND, null);
    public static final CosmeticItem RAGGED_PANTS = register("ragged_pants", CosmeticSlot.LEGS, id("drowned"));
    public static final CosmeticItem RAGGED_SHIRT = register("ragged_shirt", CosmeticSlot.CHEST, id("drowned"));
    public static final CosmeticItem RAVAGER_HORNS = register("ravager_horns", CosmeticSlot.HEAD, null);
    public static final CosmeticItem REDS_HAT = register("reds_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem RIBBONS = register("ribbons", CosmeticSlot.HEAD, null);
    public static final CosmeticItem RIDING_BOOTS = register("riding_boots", CosmeticSlot.FEET, id("bee_friender"));
    public static final CosmeticItem ROSAS_HAT = register("rosas_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem SANDALS = register("sandals", CosmeticSlot.FEET, id("wandering_trader"));
    public static final CosmeticItem SAVANNA_HAT = register("savanna_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem SAVANNA_ROBE_BOTTOM = register("savanna_robe_bottom", CosmeticSlot.LEGS, id("villager_savanna"));
    public static final CosmeticItem SAVANNA_ROBE_TOP = register("savanna_robe_top", CosmeticSlot.CHEST, id("villager_savanna"));
    public static final CosmeticItem SELENES_HAT = register("selenes_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem SEQUIN_DRESS_BOTTOM = register("sequin_dress_bottom", CosmeticSlot.LEGS, id("party_alex"));
    public static final CosmeticItem SEQUIN_DRESS_TOP = register("sequin_dress_top", CosmeticSlot.CHEST, id("party_alex"));
    public static final CosmeticItem SERENAS_HAT = register("serenas_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem SHEPHERDS_HAT = register("shepherds_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem SHOES = register("shoes", CosmeticSlot.FEET, id("steve"));
    public static final CosmeticItem SHORTS = register("shorts", CosmeticSlot.LEGS, id("villager"));
    public static final CosmeticItem SLACKS = register("slacks", CosmeticSlot.LEGS, id("zuri_default"));
    public static final CosmeticItem SLEEPING_MASK = register("sleeping_mask", CosmeticSlot.HEAD, null);
    public static final CosmeticItem SMITHING_APRON_BOTTOM = register("smithing_apron_bottom", CosmeticSlot.LEGS, id("villager_armorer"));
    public static final CosmeticItem SMITHING_APRON_TOP = register("smithing_apron_top", CosmeticSlot.CHEST, id("villager_armorer"));
    public static final CosmeticItem SNOW_HAT = register("snow_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem SNOW_ROBE_BOTTOM = register("snow_robe_bottom", CosmeticSlot.LEGS, id("villager_snow"));
    public static final CosmeticItem SNOW_ROBE_TOP = register("snow_robe_top", CosmeticSlot.CHEST, id("villager_snow"));
    public static final CosmeticItem SOMBRERO = register("sombrero", CosmeticSlot.HEAD, null);
    public static final CosmeticItem STAR_PIN = register("star_pin", CosmeticSlot.HEAD, null);
    public static final CosmeticItem STETSON = register("stetson", CosmeticSlot.HEAD, null);
    public static final CosmeticItem SUN_HAT = register("sun_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem SUNGLASSES = register("sunglasses", CosmeticSlot.HEAD, null);
    public static final CosmeticItem SWAMP_HAT = register("swamp_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem SWAMP_ROBE_BOTTOM = register("swamp_robe_bottom", CosmeticSlot.LEGS, id("villager_swamp"));
    public static final CosmeticItem SWAMP_ROBE_TOP = register("swamp_robe_top", CosmeticSlot.CHEST, id("villager_swamp"));
    public static final CosmeticItem T_SHIRT = register("t_shirt", CosmeticSlot.CHEST, id("steve"));
    public static final CosmeticItem TAIGA_ROBE_BOTTOM = register("taiga_robe_bottom", CosmeticSlot.LEGS, id("villager_taiga_default"));
    public static final CosmeticItem TAIGA_ROBE_TOP = register("taiga_robe_top", CosmeticSlot.CHEST, id("villager_taiga_default"));
    public static final CosmeticItem TALL_BOOTS = register("tall_boots", CosmeticSlot.FEET, id("alex"));
    public static final CosmeticItem TATTERED_CAP = register("tattered_cap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem TATTERED_LEGGINGS = register("tattered_leggings", CosmeticSlot.LEGS, id("husk"));
    public static final CosmeticItem TATTERED_SHIRT = register("tattered_shirt", CosmeticSlot.CHEST, id("husk"));
    public static final CosmeticItem THICK_FRAMED_GLASSES = register("thick_framed_glasses", CosmeticSlot.HEAD, null);
    public static final CosmeticItem THICK_FRAMED_SUNGLASSES = register("thick_framed_sunglasses", CosmeticSlot.HEAD, null);
    public static final CosmeticItem THICK_GLOVE = register("thick_glove", CosmeticSlot.HAND, null);
    public static final CosmeticItem THIN_FRAMED_GLASSES = register("thin_framed_glasses", CosmeticSlot.HEAD, null);
    public static final CosmeticItem THIN_FRAMED_SUNGLASSES = register("thin_framed_sunglasses", CosmeticSlot.HEAD, null);
    public static final CosmeticItem TIARA = register("tiara", CosmeticSlot.HEAD, null);
    public static final CosmeticItem TIGHTS = register("tights", CosmeticSlot.LEGS, id("bee_friender"));
    public static final CosmeticItem TOGA_BOTTOM = register("toga_bottom", CosmeticSlot.LEGS, id("villager_librarian"));
    public static final CosmeticItem TOGA_TOP = register("toga_top", CosmeticSlot.CHEST, id("villager_librarian"));
    public static final CosmeticItem TOP_HAT = register("top_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem TOQUE = register("toque", CosmeticSlot.HEAD, null);
    public static final CosmeticItem TORN_CAP = register("torn_cap", CosmeticSlot.HEAD, null);
    public static final CosmeticItem TORN_PANTS = register("torn_pants", CosmeticSlot.LEGS, id("stray"));
    public static final CosmeticItem TORN_SHIRT = register("torn_shirt", CosmeticSlot.CHEST, id("stray"));
    public static final CosmeticItem TRICORNE = register("tricorne", CosmeticSlot.HEAD, null);
    public static final CosmeticItem TUNIC = register("tunic", CosmeticSlot.CHEST, id("villager"));
    public static final CosmeticItem UMBRELLA_HAT = register("umbrella_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem VICTORS_HAT = register("victors_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem VINDICATORS_COAT = register("vindicators_coat", CosmeticSlot.CHEST, id("vindicator"));
    public static final CosmeticItem VISOR = register("visor", CosmeticSlot.HEAD, null);
    public static final CosmeticItem WADING_BOOTS = register("wading_boots", CosmeticSlot.FEET, id("villager_fisherman"));
    public static final CosmeticItem WANDERING_TRADERS_HOOD = register("wandering_traders_hood", CosmeticSlot.HEAD, null);
    public static final CosmeticItem WANDERING_TRADERS_ROBE_BOTTOM = register("wandering_traders_robe_bottom", CosmeticSlot.LEGS, id("wandering_trader"));
    public static final CosmeticItem WANDERING_TRADERS_ROBE_TOP = register("wandering_traders_robe_top", CosmeticSlot.CHEST, id("wandering_trader"));
    public static final CosmeticItem WEAPONSMITHS_EYE_PATCH = register("weaponsmiths_eye_patch", CosmeticSlot.HEAD, null);
    public static final CosmeticItem WITCHS_HAT = register("witchs_hat", CosmeticSlot.HEAD, null);
    public static final CosmeticItem WOOL_COAT_BOTTOM = register("wool_coat_bottom", CosmeticSlot.LEGS, id("villager_shepherd"));
    public static final CosmeticItem WOOL_COAT_TOP = register("wool_coat_top", CosmeticSlot.CHEST, id("villager_shepherd"));
    public static final CosmeticItem WRIST_RECOVERY_COMPASS = register("wrist_recovery_compass", CosmeticSlot.HAND, null);
    public static final CosmeticItem WRISTCOMPASS = register("wristcompass", CosmeticSlot.HAND, null);
    public static final CosmeticItem WRISTWATCH = register("wristwatch", CosmeticSlot.HAND, null);

    public static void init() {
        // trigger class loading so all fields are registered
    }

    private static Identifier id(String path) {
        return Identifier.fromNamespaceAndPath(VestureMod.MOD_ID, path);
    }

    private static CosmeticItem register(String name, CosmeticSlot slot, Identifier equipmentModel) {
        ResourceKey<Item> key = ResourceKey.create(Registries.ITEM, id(name));
        CosmeticItem item = new CosmeticItem(new Item.Properties().setId(key), slot, equipmentModel);
        Registry.register(BuiltInRegistries.ITEM, key, item);
        return item;
    }
}
